### ISSUE TITLE
Partial ordering of constraints in variadic templates is not working properly

### ISSUE THREAD

**Issue by Serikov** [saarraz/clang-concepts-old#10]
Hi, thank you for your work.

Example of error (based on non-variadic example from cppreference):
```
template<class T> constexpr bool is_meowable = true;
template<class T> constexpr bool is_cat = true;
 
template<class T>
concept Meowable = is_meowable<T>;
 
template<class T>
concept GoodMeowableCat = Meowable<T> && is_cat<T>;
 
template<Meowable... T>
void f2(T...); // #3
 
template<GoodMeowableCat... T>
void f2(T...); // #4
 
void g(){
    f2(0); // Expected: OK, calls #4, more constrained than #3
           // GoodMeowableCat got its is_meowable<T> from Meowable
           // Actual: error: call to 'f2' is ambiguous
}
```

Here is [godbolt example](https://godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAKxAEZSAbAQwDtRkBSAJgCFufSAZ1QBXYskwgA5NwDMeAGYssCgNQB9dcmZtNHAAwBBOSrwtMqgMI9VAI1SoGB411mYGgi85OYFZi9berpjKit5GBJgAtgAOzJEcspbaTIKCqgAqidiqaCyCkQAeMcR2DgyqeILqUZioAO5MtgxesgAiqgTEIpiJfBHRcUwJSSlpmdm5qPlFJWWOldXIw6qJHV09fc6rA7HxvaPM41my2M55EjEEVjYAsnWNza0dVTUPTS2Jlidnsv2GO0MkT2wwOySO6R%2B52ml2u1lUAHEHOh7g0PphLCs1qpUY9PkkfqsuAA2bjExZaYZfKF/bbOYFDEaWXHogB07Imp2cADdUHh0KoFFwIBl2ayAJR9VQAemlRNksjpu0ZYKRGBZT0xBDFnLORl5/MFwtF7MlfxlcrkABYlYYDQLgBBJQB2f6qd1GiD6M02WWqADyAGlSLkmAwPPKrSGoiQLHkCsQmP4BQQEKx5YqjB7s9m/WqUe9NStgKhroR0q9amintTJgpiKgojjC58jBxnW0pOLGNIAKxSUgsaT6AeoaSWfj8VTCMQSeW0AcEYdd7sAaxACtZCu3O93xJ7UitA6HUhHpDHUgHghA%2BlIS9PXdIcFgSDQsTwLTIFAgb5iH8wxAgMAAAcXCkH4DCRMQ14QLYy6kLYZhMMQACe0gLqQb61CwBD%2BiwDBoQ%2BpBYFErDAC08H4MQmDIAQeDcpg15EZghQ0SIkToQOZiRAw8FdHgUScd2OjsJOvCMHgtjXpA3aoFceDTExAC0CgXJgVyCFeojiJItDCX2x7wRehTAcSSnElaqjAMgyCqMBrJcKoEC4IQJDziGliNn%2Bn7zuKVhiTwi7LuKa4brIW67pFCr7rxh6GURF5Xjed7BU%2BMBQOlEBIKIBAxOx5CUL%2B/6AWBmD4EQgH0PUiYxEJB79oORnSHIjn1IQCCqCZZkWbkIlOSxMQAQJIQEGGUwsLCgjikFD4haQCCYEwWCAU6B5HqQgm9reJ5nolQjJfeI7ds%2BiAoF5xUFT%2B52figIlaDC6kEII4EflBMFwURiEsMhhEYVhI14QRlHRGRFFEVRNF0QxTFnixbEcVIGHce4fHEAJdUiSgAUSVJ8CyfJinSFps66fpUgNTto7SF15mWSkbD9cUQ3YaNFRqRpfnOeVblyPQVjXQB8pcH5E68PwM1HaFm5RVFa0Dpt21NZe%2B23odK6kOu0sy7uB6yPFu1Eyls1k1w%2BtU8ratzQx0EKUOVpAA%3D%3D)

`GoodMeowableCat` subsumes `Meowable` and f2#4 should be selected as more constrained.

**Comment by saarraz** [comment]
Hey Sekirov. 
I'm afraid this is sort of a defect in the standard - subsumption rules do not consider fold expressions (which the associated constraints of the 2 f2's are).
http://cplusplus.github.io/concepts-ts/ts-active.html#28

**Comment by Serikov** [comment]
Oh, thank you for the information.
I hope it will be resolved before C++20.
IMO it is confusing that repeating concept manually differs in behaviour from variadic template.

```
#ifndef __clang__
#define CB bool
#else 
#define CB
#endif

template<class T> constexpr bool is_meowable = true;
template<class T> constexpr bool is_cat = true;
 
template<class T>
concept CB Meowable = is_meowable<T>;
 
template<class T>
concept CB GoodMeowableCat = Meowable<T> && is_cat<T>;
 
template<Meowable T1, Meowable T2, Meowable T3, Meowable T4>
int f1(T1, T2, T3, T4)
{
    return 1;
}
 
template<GoodMeowableCat T1, GoodMeowableCat T2, GoodMeowableCat T3, GoodMeowableCat T4>
int f1(T1, T2, T3, T4)
{
    return 2;
}

template<Meowable... T>
int f2(T...)
{
    return 1;
}
 
template<GoodMeowableCat... T>
int f2(T...)
{
    return 2;
}


int g(){
    return f1(1, 2., 'c', "d"); // compiles and select GoodMeowableCat
                                // returns 2

}

int b(){
    return f2(1, 2., 'c', "d"); // is an error
}
```

**Comment by saarraz** [comment]
Indeed. I think the solution to this is to "substitute" two unique invented parameters into each variadic parameter before checking subsumption
