### ISSUE TITLE
local concept definition / different behaviour to GCC+ConceptsTS

### ISSUE THREAD

**Issue by h-2** [saarraz/clang-concepts-old#13]
The following code is accepted by GCC+ConceptsTS:
```cpp
template <typename alphabet_type>
    requires requires (alphabet_type v) { { v.to_phred() } }
constexpr underlying_phred_t<alphabet_type> to_phred(alphabet_type const & chr)
{
    return chr.to_phred();
}
```
But is rejected by clang, unless the local definition ends in a `;', i.e. this is accepted by both:
```cpp
template <typename alphabet_type>
    requires requires (alphabet_type v) { { v.to_phred() }; }
constexpr underlying_phred_t<alphabet_type> to_phred(alphabet_type const & chr)
{
    return chr.to_phred();
}
```

I don't know if clang should accept the first one, as well, but I thought, I'd let you know.

**Comment by saarraz** [comment]
http://eel.is/c++draft/expr.prim.req.compound
Shows that the former is a syntax error - GCC shouldn't accept it
