### ISSUE TITLE
ICE when using a trailing requires-expression

### ISSUE THREAD

**Issue by cjdb** [saarraz/clang-concepts-old#15]
I was able got this ICE while trying to implement a concept-checked std::invoke.
This is the closest to a minimal repro that I can give for tonight; if you'd like something smaller, please let me know.

[invoke-d8c985.cpp.txt](https://github.com/saarraz/clang-concepts/files/2390664/invoke-d8c985.cpp.txt)
[invoke-d8c985.sh.txt](https://github.com/saarraz/clang-concepts/files/2390665/invoke-d8c985.sh.txt)

**Comment by cjdb** [comment]
Minimal repro: https://godbolt.org/z/rctoId

**Comment by saarraz** [comment]
Fixed in latest commit.
