### ISSUE TITLE
Missing extension used by Ranges: `->auto&&`, `->auto&` return-type-requirements

### ISSUE THREAD

**Issue by Quuxplusone** [saarraz/clang-concepts-old#16]
https://godbolt.org/z/oqrwf0
https://godbolt.org/z/CFsTsb
```
template<class T>
concept Iterator = requires(T t) {
    { *t } -> auto&&;
};

static_assert(Iterator<int*>);  // FAILS, should succeed
```

D0896R3's `Iterator` concept [iterator.concept.iterator] uses an `->auto&&` constraint to mean "this expression needs to yield something referenceable."  `g++ -fconcepts` accepts the above code happily.  I am fairly confident that C++2a (N4762) makes the above code *ill-formed, yes diagnostic required*, but personally I would be equally happy with GCC's behavior, since it would make D0896 work.

Either Clang should accept `->auto&`, `->auto&&`, etc., and Do The Right Thing with them; or else it should diagnose it as an error. The current behavior (not diagnosing the syntax error, but also never satisfying the requirement) seems wrong to me.

**Comment by cjdb** [comment]
This might be addressed by P1084, which is not yet incorporated into the WP
(AFAIU, it's pending CWG review).

**Comment by Quuxplusone** [comment]
P1084 is awesome but I think orthogonal to this. (P1084 addresses `->Same<int&>`, `->Reference`, etc., without ampersands at the top level.)

However, I was wrong about `->auto&&` being ill-formed in C++2a. I had been expecting it to fall under the second production rule for [_return-type-requirement_](http://eel.is/c++draft/expr.prim.req.compound#nt:return-type-requirement), i.e., I was expecting `auto` to match [_constrained-parameter_](http://eel.is/c++draft/temp.param#nt:constrained-parameter). But actually `auto` is acceptable as the _trailing-return-type_ listed in the _first_ production rule — so in fact this code is well-formed C++2a, and not an extension.

**Comment by CaseyCarter** [comment]
>  this code is well-formed C++2a, and not an extension

The code is ill-formed per [[dcl.spec.auto]/5](http://eel.is/c++draft/dcl.spec.auto#5) since it uses `auto` in a context not specifically allowed by [[dcl.spec.auto]](http://eel.is/c++draft/dcl.spec.auto). [[dcl.spec.auto]/2](http://eel.is/c++draft/dcl.spec.auto#2) allows `auto` to appear in a *trailing-return-type* with a *function-declarator*, but there's no *function-declarator* in a *compound-requirement*.

The bug here is failure to diagnose the program as ill-formed.

**Comment by saarraz** [comment]
Added the diagnostic in latest commit.
