### ISSUE TITLE
Concepts as a strict types

### ISSUE THREAD

**Issue by widgetii** [saarraz/clang-concepts-old#19]
Hello, great work!

I tried to reproduce code example from last Bjarne's talk https://youtu.be/HddFGPTAmtU?t=1230 

```
#include <type_traits>

namespace detail {
    template< class T, class U >
    concept SameHelper = std::is_same_v<T, U>;
}
 
template< class T, class U >
concept Same = detail::SameHelper<T, U> && detail::SameHelper<U, T>;

template<typename T> concept Int = Same<T,int>;

void f(int&) {
}

int main() {
    Int x1 = 7;
    int x2 = 9;
    Int y1 = x1+x2;
    int y2 = x2+x1;

    f(x);
    f(y);
}
```

I'm really new to concepts and want to learn them. It seems that code have to introduce new "strict type" as "Int", but while compiling the code I get:

```
Int.cpp:32:5: error: unknown type name 'Int'; did you mean 'int'?
    Int x1 = 7;
    ^~~
    int
Int.cpp:34:5: error: unknown type name 'Int'; did you mean 'int'?
    Int y1 = x1+x2;
    ^~~
    int
Int.cpp:37:7: error: use of undeclared identifier 'x'
    f(x);
      ^
Int.cpp:38:7: error: use of undeclared identifier 'y'
    f(y);
      ^
4 errors generated.
make: *** [Int] Error 1
```

But GCC with -fconcepts can compile such code and can use new strict "Int" types. Is that problem in Clang or GCC implementation?

**Comment by cjdb** [comment]
Constrained variable type deduction is a part of the Concepts TS (hence why it works in GCC), but it has not yet been approved for C++20 (hence why it does not work with Clang). There are a lot of historical reasons for why CVTD isn't in the C++20 WP, but there is a joint proposal authored by all of the key people necessary to address this.

My advice is to do _one_ of the following until it's supported in both GCC and Clang:

```cpp
auto foo = bar(); // requires Int

// or

auto foo = bar(); static_assert(Int<std::remove_cvref_t<decltype(foo)>>); // yes, remove_cvref_t is necessary

// or

auto foo = bar(); static_assert(Int<std::remove_cv_t<std::remove_reference_t<decltype(foo)>>>); // if you can't use remove_cvref_t
```
