### ISSUE TITLE
Clang gives an error when it shouldn't

### ISSUE THREAD

**Issue by preshing** [saarraz/clang-concepts-old#20]
https://godbolt.org/z/BvR82D

- If I uncomment line 7, the error goes away
- If I replace “concept IsXXX” with “concept bool IsXXX” on lines 2 and 5, then compile with GCC 8.2 (-std=c++2a -fconcepts), there’s no error

As discussed by email: "...this is surely a bug on my part because the diagnostics produced do not explain why the type doesn't satisfy the concept. "

**Comment by saarraz** [comment]
Fixed in latest commits.
