### ISSUE TITLE
A different case of infinite template recursion

### ISSUE THREAD

**Issue by marehr** [saarraz/clang-concepts-old#25]
Hi saarraz,

we somehow stumbled into a different infinite template recursion, but I think in this case we might be right :joy: 

```c++
#include <iostream>

struct as {};

template <typename a>
std::basic_ostream<a> & operator<<(std::basic_ostream<a> & s, as) // #1
{
    s << "#1\n";
    return s;
}

template <typename au, typename av>
concept aw = requires(au c, av ax){{c << ax}->au;};

template <typename b>
    requires aw<std::ostream, b>
void operator<<(int, b); // #2

int main()
{
    std::cout << as{}; // print #1
    return 0;
}
```

https://godbolt.org/z/4GcuvB

What should happen:
`std::cout << as{};` should print `#1`, because
* the only matching signature is `#1` (`std::basic_ostream<a> & operator<<(std::basic_ostream<a> & s, as`)
* `#2` is not matching, because of the first argument `int` (`void operator<<(int, b);`).

I don't know what the standard says (is this document somewhere public?!), but from my gut feeling I would expect that the compiler first collects a list of possible matching functions (those that match the function signature) and after that looks which of them is the most specific. In this case the `<<(int, *)` operator is unrelated to the `<<(std::ostream, *)` operator.

cc: @h-2

Thank you for your help (again)!

**Comment by saarraz** [comment]
The compiler has to deduce the argument types of #2 before considering it for the overload set, and constraint checking is part of the deduction process. http://eel.is/c++draft/temp.deduct#5
Therefore it cannot rule out #2 of overload resolution without checking it's constraints, which in turn causes the same overload resolution in an infinite recursion.

**Comment by marehr** [comment]
Okay this unfortunate; Is there a way to report this as a defect in the standard?

**Comment by saarraz** [comment]
First step would be to discuss this on the std-discussion Google group.
