### ISSUE TITLE
ICE with tuple

### ISSUE THREAD

**Issue by hanickadot** [saarraz/clang-concepts-old#26]
This code will give me ICE: https://godbolt.org/z/-bFYgl
```
#include <tuple>

int main()
{
  std::tuple<int, int> t;
}
```

**Comment by saarraz** [comment]
Hi, yeah sorry about that - I accidentally pushed a bug in the latest commit. I already know what it is and have a fix, should be up in a couple hours

**Comment by hanickadot** [comment]
No problem! Thanks for the awesome work!

**Comment by saarraz** [comment]
Fixed in latest commits (godbolt might take time to update).
