### ISSUE TITLE
Allow template template parameters to be unconstraint again

### ISSUE THREAD

**Issue by marehr** [saarraz/clang-concepts-old#37]
```c++
#if __cpp_concepts == 201507 // GCC and Concepts TS
#define concept concept bool
#endif

template <typename T>
concept True = true;

template <True type>
struct my_functor
{
    constexpr auto operator()()
    {
        return 42;
    }
};

template <template <typename...> typename functor_t, typename... args_t>
struct invoker
{
    static constexpr auto value = functor_t<args_t...>{}();
};

template <template <True...> typename functor_t, True... args_t>
struct indirect_invoker
{
    static constexpr auto value = invoker<functor_t, args_t...>::value;
}; // this is not working

constexpr auto question = invoker<my_functor, int>::value;
```

I think in this case the implementer of `invoker` should enforce some kind of concept test, because every class which uses the invoker might impose different constraints on the template template parameter of `invoker`.

https://godbolt.org/z/dN3jWe

```c++

template <template <typename...> typename functor_t, typename... args_t>
concept InvocableFunctor = requires()
{
    { functor_t<args_t...>{}() };
};

template <template <True...> typename functor_t, True... args_t>
requires InvocableFunctor<functor_t, args_t...>
struct indirect_invoker_with_concept
{
    static constexpr auto value = functor_t<args_t...>{}();
}; // this is not working, but I can't give constraints within a concept definition

```

This would be a possible concept check to see if the invoker call works (which should call its own concept check).

But, this also gives me an error because I can't even constraint the template template parameter in the concept definition due to #31.

**Comment by marehr** [comment]
I forgot to add that I encountered this issue when building the meta library in https://github.com/CaseyCarter/cmcstl2

**/cc** @cjdb

**Comment by saarraz** [comment]
The following is legal and is accepted in the current implementation:
```
template<template<True...> typename functor_t, typename... args>
concept InvocableFunctor = requires(functor_t<args...> t) {
    t();
};
```
You can constrain the parameters of the template template parameter, but not add a constraint to the template itself. In some way the constraints of the parameter functor_t are part of the "template signature" of InvocableFunctor, meaning they allow/disallow certain parameters from being passed in to the concept altogether (not even yielding false for them). For example, you couldn't pass into the InvocableFunctor concept a class template which is more constrained than `template<True...> class f{};`.

**Comment by marehr** [comment]
But isn't `template<typename...> class g{};` less constraint?

**Comment by marehr** [comment]
I tried your version: https://godbolt.org/z/quQs3x

and it still does not work

```c++
<source>:15:27: error: template template argument 'functor_t' must not be more constrained than template template parameter 'functor_in_concept_t'
requires InvocableFunctor<functor_t, args_t...>
                          ^~~~~~~~~

<source>:8:37: note: 'functor_in_concept_t' declared here
template<template<True...> typename functor_in_concept_t, typename... args>
                                    ^

<source>:14:39: note: 'functor_t' declared here
template <template <True...> typename functor_t, True... args_t>
                                      ^

1 error generated.
Compiler returned: 1
```

**Comment by Quuxplusone** [comment]
I believe I'm seeing the same issue. https://godbolt.org/z/I8z3RT
```
template<class T>
concept True = true;

template<template<True> class C>
struct dummy { 
    using type = C<int>;
};
```

GCC likes this code; Clang doesn't like it. Clang's error message is also definitely incorrect — there shouldn't be _any_ types that don't satisfy `True` — and I think it might arguably be premature, since my test case never instantiates template `dummy`.

```
6:18: error: constraints not satisfied for template template parameter 'C' [with $0 = int]
    using type = C<int>;
                 ^~~~~~
<source>:4:19: note: because 'type-parameter-0-0' does not satisfy 'True'
template<template<True> class C>
                  ^
1 error generated.
Compiler returned: 1
```

**Comment by saarraz** [comment]
@marehr My solution indeed does not work, and I believe the standard does not allow the kind of checks you want to perform, unfortunately.
@Quuxplusone Fixed the bug with latest commit.
