### ISSUE TITLE
Nitpick: Concept is referred to as a "class template" in error message

### ISSUE THREAD

**Issue by Quuxplusone** [saarraz/clang-concepts-old#39]
```
template<class> concept C = true;
static_assert(C);
```
```
<source>:3:15: error: cannot refer to class template 'C' without a template argument list
static_assert(C);
              ^
<source>:2:25: note: template is declared here
template<class> concept C = true;
                        ^
1 error generated.
```

I think "`class template 'C'`" should say "`concept 'C'`" instead.

**Comment by saarraz** [comment]
Fixed in latest commit.

**Comment by FirstLoveLife** [comment]
Hi, saarraz, thanks for your awesome work for clang-concept. Can you specify which commit fixed this issue (a link is enough) instead of `latest commit`?

no offense at all, just think it will be much easier for other people to learn something from the issue tracker.

**Comment by saarraz** [comment]
Sure, I'll make sure to do that for upcoming fixes.
