### ISSUE TITLE
Incorrect "is more specialized" logic for non-concept requires expressions

### ISSUE THREAD

**Issue by kjcamann** [saarraz/clang-concepts-old#47]
This code:

```{.cpp}
#include <type_traits>

template <typename T>
    requires std::is_integral_v<T>
struct S {
};

template <typename T>
    requires std::is_integral_v<T> && std::is_unsigned_v<T>
struct S<T> {
};
```

produces this error:

```
clang-concepts.cpp:10:8: error: class template partial specialization is not more
    specialized than the primary template [-Winvalid-partial-specialization]
struct S<T>
       ^
```

If you factor the requires expressions into concept definitions first, then it works fine. I am not sure if this is a bug or if normalization of non-concept expressions is just not implemented yet.

**Comment by saarraz** [comment]
It's neither - this is correct behavior.
Two atomic constraints that are identical - here std::is_integral_v<T> are not considered equivalent for more-constrained logic unless they actually come from the same source-level place.
I know this is kind of counter-intuitive, but that's the way the standard defines this.
Anyway, I added an error message in the latest commit dcb8352231cbe988828220f89c04e9595d633beb that explains the misunderstanding:
```
/github_47.cpp:10:8: error: class template partial specialization is not more specialized than the primary template [-Winvalid-partial-specialization]
struct S<T> {
       ^
/github_47.cpp:5:8: note: template is declared here
struct S {
       ^
/github_47.cpp:4:14: note: 'std::is_integral_v<T>' in the two declarations is not considered equivalent - move it to a concept and
      reference it from here:
    requires std::is_integral_v<T>
             ^
/github_47.cpp:9:14: note: and here
    requires std::is_integral_v<T> && std::is_unsigned_v<T>
             ^
```
When godbolt updates, you'll be able to see the new error message here https://godbolt.org/z/vdDpO3

**Comment by kjcamann** [comment]
I guess that's what I get for reading only the first page of P0717, I see now it's summarizing how it used to work in the concepts TS and then they changed it to what you just explained; that explains why gcc's TS-based implementation still accepts it. Thanks for the clarification -- and for all your work on clang concepts in general!
