### ISSUE TITLE
Updating to newer LLVM/Clang

### ISSUE THREAD

**Issue by tzakharko** [saarraz/clang-concepts-old#48]
Concepts implementation is currently merged agains a late 2017 version of LLVM/Clang. I was wondering what were your plans in updating to the more recent codebase? I tried to merge your changes on top of  LLVM7.0 and I even got it to compile, but since I have no idea about LLVM or Clang design, some merging decision I made were arbitrary and the resulting compiler was rather  dysfunctional.

**Comment by saarraz** [comment]
Hi! I was planning to do the merge in the next couple of weeks.
Indeed I will do it in steps as there are probably some changes that
require attention. I'll probably have something by the end of March if not
sooner

**Comment by tzakharko** [comment]
Great to know! Looking forward to it and thank you for the incredible work!

**Comment by marehr** [comment]
@saarraz Did you find some time for the rebase?

**Comment by saarraz** [comment]
Barely, but I'm almost done with it. I'm taking some time off next week so
it'll be surely done by then

**Comment by saarraz** [comment]
Done!
