### ISSUE TITLE
Requires expression with negation does not compile

### ISSUE THREAD

**Issue by uap-universe** [saarraz/clang-concepts-old#49]
I tried to compile the [reference implementation for ranges](https://github.com/CaseyCarter/cmcstl2) and it fails for several reasons. One of them is the usage of negation within a requires expression.

The resulting error is:
> error: expected primary expression before '!'

Occurring here:
> ebo_box.hpp:37:13:
> requires !_OneOf<std::decay_t<First>, ebo_box, T>

And here:
> ebo_box.hpp:61:39:
> requires std::is_empty<T>::value && !std::is_final<T>::value

I also believed that requires expressions must be in positive normal form, but this seems not to be the case (unless cmcstl2 contains ill-formed code, which I think is very unlikely).

### Version Information:
clang-concepts: 1239b329045d7be60f20eec9d3a4622b07b9b81f built against llvm 893a41656b527af1b00a1f9e5c8fcecfff62e4b6 as suggested.
cmcstl2 version: fb1b65b006e5df4be205cf538e360f8d16cda3ca

**Comment by CaseyCarter** [comment]
> unless cmcstl2 contains ill-formed code, which I think is very unlikely

I'd like to think so as well, but this one is my bug - not @saarraz's. Fixed in https://github.com/CaseyCarter/cmcstl2/commit/96032413a75ccb267de9f8255f5d10998cde1185.

**Comment by uap-universe** [comment]
Ah wonderful, thank you.

**Comment by improbable-nickkrempel** [comment]
Isn't this working as intended, according to the current draft standard? `requires` takes a (`||` and `&&` combination of) _primary-expression_, meaning parentheses are required to use `!`, like this: `requires (!...)`.

Also see the non-normative note:
> _Note_: The expression in a _requires-clause_ uses a restricted grammar to avoid ambiguities. Parentheses can be used to specify arbitrary expressions in a _requires-clause_.

**Comment by CaseyCarter** [comment]
> Isn't this working as intended, according to the current draft standard?

Yes, it is. I suppose I should have made that clear in my reply. cmsctl2 was originally written in Concepts TS concepts, not C++20 concepts, and some parts haven't yet been updated to conform to both sets of requirements.
