### ISSUE TITLE
Substitution into concepts doesn't properly short-circuit

### ISSUE THREAD

**Issue by CaseyCarter** [saarraz/clang-concepts-old#5]
The example from [[temp.constr.op]/4](http://eel.is/c++draft/temp.constr.op#4) fails to compile (https://godbolt.org/g/SnWD3k):
```c++
template<typename T>
constexpr bool get_value() { return T::value; }

template<typename T>
  requires (sizeof(T) > 1) && get_value<T>()
void f(T); // has associated constraint sizeof(T) > 1 ^ get_value<T>()
void f(int);

int main() { f('a'); }
```
Since `sizeof(T) > 1` is `false` for `char`, template argument should not be substituted into the subsequent constraints.

**Comment by saarraz** [comment]
Solved in latest commit to `concepts`
