### ISSUE TITLE
Identifiers used in requires clause which are declared as function parameters are considered undeclared

### ISSUE THREAD

**Issue by uap-universe** [saarraz/clang-concepts-old#50]
I tried to compile the [reference implementation for ranges](https://github.com/CaseyCarter/cmcstl2) and encountered the following error (paths shortened):

<pre>
In file included from .../cmcstl2/include/experimental/ranges/concepts:12:
In file included from .../cmcstl2/include/stl2/concepts.hpp:15:
.../cmcstl2/include/stl2/detail/swap.hpp:147:5: error: use of undeclared identifier 'x'
                               x.derived().swap(y.derived())
                               ^
.../cmcstl2/include/stl2/detail/swap.hpp:147:22: error: use of undeclared identifier 'y'
                               x.derived().swap(y.derived())
                                                ^
</pre>
The code in question is the following:

```C++
friend constexpr void swap(__member_swap& x, __member_swap& y)
STL2_NOEXCEPT_REQUIRES_RETURN(
        x.derived().swap(y.derived())
)
```

After expansion:
```C++
friend constexpr void swap(__member_swap& x, __member_swap& y)
noexcept(noexcept(x.derived().swap(y.derived()))) 
        requires requires {x.derived().swap(y.derived()); }
        { return x.derived().swap(y.derived()); }
```

I think the problem is, that neither `x`, nor `y` are local variables in the nested requires expression, but declared in the enclosing context (here: the function parameters).

The [proposal](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2017/n4674.pdf) says under [expr.prim.req]:

> The requirement-body is comprised of a sequence of requirements. These requirements may refer to local parameters, template parameters, and **any other declarations visible from the enclosing context**.

So if I am not mistaken, the identifiers `x` and `y` should be considered declared in this context.

### Version Information:
clang-concepts: 1239b329045d7be60f20eec9d3a4622b07b9b81f built against llvm 893a41656b527af1b00a1f9e5c8fcecfff62e4b6 as suggested.
cmcstl2 version: fb1b65b006e5df4be205cf538e360f8d16cda3ca

**Comment by tzakharko** [comment]
Note that it does work as expected for function templates: 

    template<typename T>  
    auto stuff(T x) ->T requires requires { {x+1}->T;} {
       return x+1;
    }

I assume that template functions are treated differently somehow when the requires clause is processed.

**Comment by saarraz** [comment]
Solved in latest commit.
