### ISSUE TITLE
logical `not` not working?

### ISSUE THREAD

**Issue by marehr** [saarraz/clang-concepts-old#52]
The following code gives me an error (https://godbolt.org/z/szmUAI):

```c++
template <typename t>
    requires !false
int foo()
{
    return 1;
}

int main()
{
    return foo<int>();
}
```

```c++
requires true && !false // is also not working
```

```log
<source>:2:14: error: expected primary expression before '!'; did you forget parentheses?
    requires !false
             ^
1 error generated.
Compiler returned: 1
```

**Comment by saarraz** [comment]
This is indeed invalid syntax without parentheses - you can only use very
simple expressions in requires clauses without parentheses. The error
message also suggests you add them

**Comment by marehr** [comment]
Oh, thank you!

I read on https://en.cppreference.com/w/cpp/language/constraints#Requires_clauses and it says that it must be a series of `primary expressions` between `&&` and `||`.

So that makes `requires !false` not a primary expression. This is really confusing, but okay.

**Comment by marehr** [comment]
Just to make sure:

An expression like 
* `requires (!literal1) && (!literal2)` is the same as
* `requires (!literal1 && !literal2)` 

in the context of subsumption? So is it safe to wrap all expressions with parentheses in a requires clause?

**Comment by saarraz** [comment]
Yes, subsumption looks through parentheses
