### ISSUE TITLE
`cannot yet mangle expression type ConceptSpecializationExpr`

### ISSUE THREAD

**Issue by marehr** [saarraz/clang-concepts-old#53]
Not sure what this means and how I can workaround it.

I tried to compile the ranges library (concept branch) with clang-concepts.

```c++
range-v3/include/range/v3/range/dangling.hpp:43:43: error: cannot yet mangle expression type ConceptSpecializationExpr
        using maybe_dangling_ = if_then_t<ForwardingRange_<R>, U, dangling>;
```

See https://github.com/ericniebler/range-v3/blob/36c651faeb5c81bc28ac9ffcd97ad0602f2fade4/include/range/v3/range/dangling.hpp#L28-L44 for the original code

Here is the part after preprocessor:

```c++
    struct dangling
    {
        dangling() = default;

        template<typename T>
        constexpr dangling (T &&) requires NotSameAs_<T, dangling>
        {}
    };

    namespace detail
    {
        template<class R, class U> requires Range<R>
        using maybe_dangling_ = if_then_t<ForwardingRange_<R>, U, dangling>;
    }
```

**Comment by saarraz** [comment]
Can you produce a minimal snippet that triggers the error?

**Comment by marehr** [comment]
Yeah, I will run creduce.

**Comment by marehr** [comment]
Here you are:

```c++
#ifndef __clang__
#define concept concept bool
#endif
namespace a {
template <bool> struct b {};
template <typename> concept c = true;
struct {
  template <typename d = int> auto operator()() -> b<c<d>>;
} e;
} // namespace a
void fn1() { a::e(); }
```

```
<source>:5:54: error: cannot yet mangle expression type ConceptSpecializationExpr
  template <typename d = int> auto operator()() -> b<c<d>>;
                                                     ^~~~~
1 error generated.
Compiler returned: 1
```

https://godbolt.org/z/09xVQG

**Comment by marehr** [comment]
@saarraz What do you think? Is this case an error on our side, or a bug?

**Comment by saarraz** [comment]
Didn't look at this yet, so I'm not sure. Been busy on fixing CR comments
to get this merged to trunk.
I'll let you know when I get a chance to debug this.

**Comment by h-2** [comment]
Any news on this? 

Thank you for working on bringing concepts to clang!

**Comment by saarraz** [comment]
Hey, solved in latest commit. So sorry this took so long, I had barely any time to work on this in the past month.
