### ISSUE TITLE
`this` not supported in requires clauses

### ISSUE THREAD

**Issue by improbable-nickkrempel** [saarraz/clang-concepts-old#56]
For example:

```
struct Foo {
    void bar() requires(sizeof this == 4) {}
};
```

gives the error `error: invalid use of 'this' outside of a non-static member function`. (https://gcc.godbolt.org/z/8_j4oO)

The standards (current draft N4810, but this particular wording goes back to C++11) indicate this is permitted in `[expr.prim.this]`:

> If a declaration declares a member function or member function template of a class X, the expression _this_ is a prvalue of type “pointer to _cv-qualifier-seq_ X” between the optional _cv-qualifier-seq_ and the end of the _function-definition_, _member-declarator_, or _declarator_.

gcc trunk (but not 8.3) allows this usage of `this` (with `-fconcepts`). It seems intentional to allow it, in the same way `this` can be used in trailing return types and `noexcept` clauses.

**Comment by CaseyCarter** [comment]
This is particularly interesting after fixing #50: access to class members works, but *not* when qualified with `this->` (https://godbolt.org/z/pA-aT4):
```c++
struct S {
    int i = 42;

    template<class T>
    auto f(T t) requires requires { i + t; } { // Fine
        return i + t;
    }

    template<class T>
    auto g(T t) requires requires { this->i + t; } { // Explodes
        return this->i + t;
    }
};

int main() {
    S s;
    return s.f(42) - s.g(42);
}
```

**Comment by saarraz** [comment]
Fixed in latest commits.
