### ISSUE TITLE
Crash when attempting to use a concept in a function declaration

### ISSUE THREAD

**Issue by jorgbrown** [saarraz/clang-concepts-old#57]
```
namespace std {
    template<class B> concept Boolean = sizeof(B) == 1;
}  // nanmespace std

void Alpha(std::Boolean auto && c);
```

Crashes : https://godbolt.org/z/X9QYtm

**Comment by saarraz** [comment]
Hi, this shorthand syntax is not implemented yet unfortunately. You can use
the concept in the template parameter list or requires clause but not
before `auto` just yet.
