### ISSUE TITLE
Inconsistent free function detection

### ISSUE THREAD

**Issue by JCBurnside** [saarraz/clang-concepts-old#59]
It will behave differently if a free function is declared inside a namespace before the concept vs after.  This does not affect free functions in the global namespace.  Example shown at [this godbolt](https://gcc.godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAKxAEZSAbAQwDtRkBSAJgCFufSAZ1QBXYskwgA5NwDMeFsgYisAag6yAwiIJ4GhAJ4bsHAAwBBOQqUrM6rQQMAHTAH0CxJoUHGzlrvKKymoamniogh6YTAC2vhZ%2BSkyCgqoAyuoA7HyZACIaPAD0haoA7noMqghMAG52AGaoqCAgwjFu9SKKEGgskencAGwAlInMKaoAKlk5%2BbJFJeUMldV1qo3Nrajtrp3dvf2TQ8OqAEY6qlhJxJjoZ5iNN6oECHa9Ek4Eqax3bR1dyB6qD6BCmx0umGut1UTHqBEwxGer1U70wnx8CQsLFimEETiYEnWTRm6kx5lUFNUNVQeF%2B23%2B3Ui6BaLBEy0%2BxHco3mqmKVQRdiIqmAeDWTAh9QUTF0wKJiNRn1UAAlkgAxG6YVUAgDqhAQADkcXiCZg/JSqTS6Ts9oCDqCjlwRgU/Bw8i6LPCYk5mPDQo4XNj2qpNPFzArQSrBOrMJqAfZcqobgBHER4G6CIEg4NDGGjBLZM2Uv67AEQJjcvj5uaVywezBen2mhzOTCBuwh2QmCzh5VqjVaxS6l6G9rGwkaBPJ1PpzP9EOO3MugsWc0bFrFm1litL6vu8xtscNJpLmvm6m01Qb0t2gaOvPkymu0%2BPt1Vvfnu5rrbW6/Aw7HE891dfIyQ/S96RLfY/3tAD8xrYC9wUUEYi8FgIBOJ9CwpERBAUYBVAPfFCSZZ0VyLAhmRQUQCFCUImRaU4mmYBgnGqLDzXsDtNF7KN%2BwBUI0mMTjQlUMAZAAVk0FgxN5Ep6iYBhBFNMiOOErQeOjWNFFCI5OzU7ixI4STpKkWTnmIERlIfVTaPUyNNIHZAhwNI0iKbTRBL02yDIkqSZL5QQEFEBg7lOQULLsc5QTwVJ5MUqzVIpbyNL4wc9RHXE3J03weT5DxLPYm4CDEFhVFMUjLDyKRhkYaRxKkUgWGkUwGuaKR5z4XhwLEccAloBqCGa6qaoAaxAcTTFqqQABYGqaqQWtINqGsEEBJsGhbqtIOBYBgRAqK9PQEXISg0EOhgERQZg2FccNBFISUGHhYhVogU4htIU4pWIAxpH60gzvaFgCAAeRYBhfs20gsBQtgLo%2B/AbmQXQ6lWqHMAAD0hHRJChpDMAYD79FOTwfs0DBcf%2Bjw8BiP6tuu9h%2BH4Rg8FOVbIBq1BPnCPppAAWhI2Rck4Xh%2BC4cU%2BZB2QVtEcRJFoGrCakerGo%2BtqMYADkGPnBmmlEGdUCBMZcYgadbAgFJRYEPi%2BE4IFwQgSHUPrSGDbYnCOxE5AV7NRd4AahuGGrXiYLBiEoUbxsmpXZtIWmJtVqHlqENbSA2lqap2/bqKcHQTqBc7LvoW5HfD%2BhSk8Jw6cVuq5rV6RvbKPVVE17Xdf11h8KNjGTbN4HLbu4YA82oPSBDsOI6m2P48m%2BbFuT1b1sDyOE6V6XE/n6Rh4zmupC4Ouk63tPl9IOoXp5kBpqAA%3D). Not sure if this is intentional or a bug.

**Comment by saarraz** [comment]
Looks like a bug, thanks :)

**Comment by JCBurnside** [comment]
Also is it a bug that the at least one overload of the function must be declared before the concept in order to use as part of the requires body?

**Comment by saarraz** [comment]
This issue is in fact not a bug - as per http://eel.is/c++draft/temp.nondep, the name resolution is made at the point the concept is defined, and only entities (overloads included) declared by that point are considered (verified this with Richard Smith).

**Comment by JCBurnside** [comment]
wouldn't that mean it detecting the overloaded free functions in the global namespace is a bug?
