### ISSUE TITLE
Atomic constraint identity erroneously sensitive to unreferenced concept arguments

### ISSUE THREAD

**Issue by hubert-reinterpretcast** [saarraz/clang-concepts-old#61]
According to N4810 [temp.constr.atomic]/1:
> An _atomic constraint_ is formed from an expression `E` and a mapping from the template parameters that appear within `E` to template arguments involving the template parameters of the constrained entity, called the _parameter mapping_.

In other words, atomic constraints emanating from a concept definition are considered identical if the target of the parameter mappings are equivalent. This may occur even if the sources of the atomic constraints involve applying different parameter lists to the concept definition.

Thus, given:
```
template <typename T> constexpr bool B = true;
template <typename T, typename U> concept C0 = B<T>;
template <typename T, typename U> concept C1 = C0<T, U> && C0<U, T>;

template <typename T, typename U> struct A;
template <typename T, typename U>
void foo(A<T, U> *) requires C1<T, T>; // B<T> && B<T>
template <typename T, typename U>
void *foo(A<T, U> *) requires C1<T, U>; // B<T> && B<U>

int main(void) { void *p = foo(static_cast<A<short, bool> *>(0)); }
```
the `void *`-returning candidate is more specialized.

The output from Compiler Explorer indicates:
```
<source>:11:28: error: call to 'foo' is ambiguous
```

Removing the extra parameter from `C0` and adjusting the use thereof makes the program compile with this Clang implementation.

Version info:
```
clang version 9.0.0 (https://github.com/saarraz/clang-concepts.git 5717663d8d0c41a9b929234475bbc94bd3bfd164) (https://github.com/llvm-mirror/llvm.git b182ab7d784ff9f8da60cc0c1329633043c0485e)
```

**Comment by saarraz** [comment]
Fixed in latest commit.
