### ISSUE TITLE
Concepts sometimes ignored when mixing friend functions with non-friend free functions

### ISSUE THREAD

**Issue by davidstone** [saarraz/clang-concepts-old#62]
```
template<typename>
struct S {
    template<typename T> requires false
    friend constexpr auto f(S, T) {
        return false;
    }
};

template<typename T, typename U>
constexpr auto f(S<T>, S<U>) {
    return true;
}

static_assert(f(S<int>{}, S<int>{}));
```

This complains about:

> <source>:14:35: error: call of overloaded 'f(S<int>, S<int>)' is ambiguous
> 
>    14 | static_assert(f(S<int>{}, S<int>{}));
> 
>       |                                   ^
> 
> <source>:10:16: note: candidate: 'constexpr auto f(S<T>, S<U>) [with T = int; U = int]'
> 
>    10 | constexpr auto f(S<T>, S<U>) {
> 
>       |                ^
> 
> <source>:4:27: note: candidate: 'constexpr auto f(S< <template-parameter-1-1> >, T) [with T = S<int>; <template-parameter-1-1> = int; S< <template-parameter-1-1> > = S<int>]'
> 
>     4 |     friend constexpr auto f(S, T) {
> 
>       |                           ^
> 
> Compiler returned: 1
> 

See it live: https://godbolt.org/z/24A0YI

**Comment by saarraz** [comment]
Can't reproduce the problem in the latest commit... Maybe it was a consequence of one of the other bugs solved lately.
Tell me if this resurfaces.
