### ISSUE TITLE
compound requirement trailing-return-type with type-constraint: additional reference is considered a syntax error

### ISSUE THREAD

**Issue by uap-universe** [saarraz/clang-concepts-old#63]
Consider the following reduced example:

```C++
#include <type_traits>

template<class U, class V>
concept Same = std::is_same_v<U,V>;

template<class I>
concept Foo =
  requires(I i) {
    { ++i } -> Same<I>&;
//                    ^-- the compiler complains about this ampersand
  };

```

Exact error message:

    error: expected ';' at end of requirement

The same is true for rvalue-references.

Tested with version 1af9c30692b10810e9eced994bbbf69db2f17e27

Please apologize, if you are already aware of such minor things and already working on it. Please leave a comment, if reports like this are more helpful or more harmful to your work, so I can adjust. Thank you :-)

**Comment by saarraz** [comment]
Hi! I'm happy to receive all reports, they are always helpful. Thanks
I'm afraid this particular syntax is no longer valid. You need to add an 'auto' before the ampersand. Unfortunately this syntax is not supported yet so the repo is in an unfortunate state where you can't exactly achieve what you want. You can either drop the ampersand right now or wait until the auto syntax is implemented (am working on it right now)

**Comment by uap-universe** [comment]
Oh, it seems I have missed that this syntax is already invalid. I thought it is discouraged as of [P1084](https://wg21.link/P1084), but still working syntax. It seems I got sth. wrong here.

My guess is, that the above example should be corrected by moving the ampersand: `{ ++i } -> Same<I&>`. So I think the support of `auto` is not required in this case.

Currently `__cpp_concepts == 201707L`. My guess is, as soon as `__cpp_concepts >= 201811L`, most of the compiler errors I see will automagically disappear, because of [this](https://github.com/CaseyCarter/cmcstl2/blob/f08d2595f75bca1b8f3b5ed717f62b7d5e6c2295/include/meta/meta_fwd.hpp#L164) feature test. So I'll be patient.

If you don't want this issue to remain open as a reminder or so, I think it can be closed.
