### ISSUE TITLE
Building fails with lldb or clang-tools-extra

### ISSUE THREAD

**Issue by adam-r-kowalski** [saarraz/clang-concepts-old#66]
I am only able to get the build to finish without any errors when not building with either lldb or clang-tools-extra. To help reproduce the issue here are the concrete steps that I have tried to build from source.

```
git clone https://github.com/llvm-mirror/llvm.git
cd llvm
git reset --hard b182ab7d784ff9f8da60cc0c1329633043c0485e
cd tools
git clone https://github.com/saarraz/clang-concepts.git clang
git clone https://github.com/llvm-mirror/lldb.git 
cd clang/tools/
git clone https://github.com/llvm-mirror/clang-tools-extra.git extra
cd ../../../projects
git clone https://github.com/llvm-mirror/libcxx.git
git clone https://github.com/llvm-mirror/libcxxabi.git
cd ..
mkdir build
cd build
cmake -G Ninja -DCMAKE_BUILD_TYPE=Release ..
ninja
```

When I remove both lldb and clang-tools-extra I can build without issues, but when you remove just one of the two it fails, and if you leave both it also fails. I would really appreciate any advice regarding how to resolve this issue.

**Comment by saarraz** [comment]
I did not verify this yet, but my guess is that you need the correct
versions of those other repositories as well.
To do this, find the commits in those repositories that were made as close
(in time) to the time commit b182ab7d784ff9f8da60cc0c1329633043c0485e was
made in llvm mirror and try again.

**Comment by adam-r-kowalski** [comment]
Thanks for the quick reply.

I went digging and found out that the commit `b182ab7d784ff9f8da60cc0c1329633043c0485e` happened on `Tue Apr 9 20:02:23 2019 +0000`

I found all the commits around that point in time for `clang-tools-extra` and I found `da7ff1f673cae5de55a2ab2f96611e92a05d9abf` which is from `Mon Apr 8 14:53:16 2019 +0000`. This worked, and I was able to get tools like clangd to work so I actually get language server support in vim! Other tools such as clang-format don't seem to like concepts yet so I need to surround them with `// clang-format off`.

I was not able to get lldb to build, and I have tried numerous commits. I tried commits around April 9th, earlier that week, and I even tried going as far back as early March. I did not have any success yet. Do you know what commit you happened to be using for lldb?

Thanks again for the help

**Comment by saarraz** [comment]
I did not compile lldb with concepts.. Can you show me the compile errors
you're getting?

**Comment by adam-r-kowalski** [comment]
I removed lldb before I rebuilt for the final time to get it work successfully. I'll kick off another build with lldb added soon and paste the logs here!

**Comment by adam-r-kowalski** [comment]
Here is the output of building with pretty much any commit around that time. I'm not sure that applying the changes recommended in the error is a good idea because then you diverge from the codebase. If we modify the past but new changes keep happening on trunk, it's only going to get harder and harder to update in the future. But i'm curious what you would recommend?

```
[60/547] Building CXX object tools/lldb/source/Symbol/CMakeFiles/lldbSymbol.dir/ClangASTContext.cpp.o
FAILED: tools/lldb/source/Symbol/CMakeFiles/lldbSymbol.dir/ClangASTContext.cpp.o
/Users/adamkowalski/llvm/build/bin/clang++  -DGTEST_HAS_RTTI=0 -DHAVE_ROUND -DLIBXML2_DEFINED -DLLDB_CONFIGURATION_RELEASE -DLLDB_USE_OS_LOG -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -Itools/lldb/source/Symbol -I../tools/lldb/source/Symbol -Itools/lldb/include -I../tools/lldb/include -I/usr/include/libxml2 -Iinclude -I../include -I/usr/include/python2.7 -I../tools/clang/include -Itools/lldb/../clang/include -I../tools/lldb/source/. -fPIC -fvisibility-inlines-hidden -Werror=date-time -Werror=unguarded-availability-new -std=c++11 -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -pedantic -Wno-long-long -Wimplicit-fallthrough -Wcovered-switch-default -Wno-noexcept-type -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wstring-conversion -fdiagnostics-color -Wno-deprecated-declarations -Wno-unknown-pragmas -Wno-strict-aliasing -Wno-deprecated-register -Wno-vla-extension -O3 -DNDEBUG    -fno-exceptions -fno-rtti -MD -MT tools/lldb/source/Symbol/CMakeFiles/lldbSymbol.dir/ClangASTContext.cpp.o -MF tools/lldb/source/Symbol/CMakeFiles/lldbSymbol.dir/ClangASTContext.cpp.o.d -o tools/lldb/source/Symbol/CMakeFiles/lldbSymbol.dir/ClangASTContext.cpp.o -c ../tools/lldb/source/Symbol/ClangASTContext.cpp
../tools/lldb/source/Symbol/ClangASTContext.cpp:1546:38: error: too few arguments to function call, expected 10, have 9; did you mean 'clang::OMPDependClause::Create'?
      template_param_decls.push_back(TemplateTypeParmDecl::Create(
                                     ^~~~~~~~~~~~~~~~~~~~
                                     clang::OMPDependClause::Create
../tools/clang/include/clang/AST/OpenMPClause.h:3527:27: note: 'clang::OMPDependClause::Create' declared here
  static OMPDependClause *Create(const ASTContext &C, SourceLocation StartLoc,
                          ^
../tools/lldb/source/Symbol/ClangASTContext.cpp:1567:38: error: too few arguments to function call, expected 10, have 9; did you mean 'clang::OMPDependClause::Create'?
      template_param_decls.push_back(TemplateTypeParmDecl::Create(
                                     ^~~~~~~~~~~~~~~~~~~~
                                     clang::OMPDependClause::Create
../tools/clang/include/clang/AST/OpenMPClause.h:3527:27: note: 'clang::OMPDependClause::Create' declared here
  static OMPDependClause *Create(const ASTContext &C, SourceLocation StartLoc,
                          ^
2 errors generated.
[69/547] Building CXX object tools/lldb/source/Target/CMakeFiles/lldbTarget.dir/ObjCLanguageRuntime.cpp.o
ninja: build stopped: subcommand failed.
```

**Comment by adam-r-kowalski** [comment]
Following your latest post on slack I grabbed the newest commit matching that which is posted on [compiler explorer](https://github.com/mattgodbolt/compiler-explorer-image/blob/master/clang/build/build-concepts.sh) `d5826c99ce56037aa7a1434717cd291522ec4613`.

This let me build using the latest commit of clang tools extra, but lldb still doesn't build.

The terse notation also now works!! I will close this issue as it seems the core is resolved.

**Comment by saarraz** [comment]
What's the error you're getting now?

**Comment by tzakharko** [comment]
Just FYI (not critical), I am building current clang-concepts (7dd64003b1659ec306875c2c78c7ce553459b1a1) with the matching LLVM monorepo (b26f96c601df5c93b6d62552b641cbf08890f621) and the LLDB fails to build here as well. Errors:

```
llvm-monorepo/lldb/source/Symbol/ClangASTContext.cpp:1558:38: error: too few arguments to function call, expected 10, have 9; did you mean
      'clang::OMPDependClause::Create'?
      template_param_decls.push_back(TemplateTypeParmDecl::Create(
                                     ^~~~~~~~~~~~~~~~~~~~
                                     clang::OMPDependClause::Create


LLVM/clang-concepts/include/clang/AST/OpenMPClause.h:3957:27: note: 'clang::OMPDependClause::Create' declared here
  static OMPDependClause *Create(const ASTContext &C, SourceLocation StartLoc,
                          ^


llvm-monorepo/lldb/source/Symbol/ClangASTContext.cpp:1579:38: error: too few arguments to function call, expected 10, have 9; did you mean
      'clang::OMPDependClause::Create'?
      template_param_decls.push_back(TemplateTypeParmDecl::Create(
                                     ^~~~~~~~~~~~~~~~~~~~
                                     clang::OMPDependClause::Create


clang-concepts/include/clang/AST/OpenMPClause.h:3957:27: note: 'clang::OMPDependClause::Create' declared here
  static OMPDependClause *Create(const ASTContext &C, SourceLocation StartLoc,
```

P.S. (Maybe it would be a good idea to mention the monorepo revision on the clang-concepts GitHub, its much easier to use that than to gather all the tools manually)

**Comment by saarraz** [comment]
I'll move to the monorepo soon.
The errors you sent helped me figure out where the problem is! I'll solve
it soon and let you know
