### ISSUE TITLE
Missing feature: explicit class template specializations

### ISSUE THREAD

**Issue by akrzemi1** [saarraz/clang-concepts-old#7]
First of all, thanks for implementing concepts, and congratulations for getting the implementation to this stage.
I think one feature from the latest draft (N4750 at the time of submitting the issue) is still missing.

An explicit instantiation of a class template shall not instantiate (non-template) member functions whose constraints are not satisfied. Here's an illustration:

```c++
template <typename T>
concept Comparable = requires(T a) { {a == a} -> bool; };

template <typename T> 
struct W
{
  T val;
 
  bool operator==(W const& y) const  // non-template constrained member
    requires Comparable<T>   
  { return this->val == y.val; }
};

struct X {};
static_assert(!Comparable<X>);
static_assert(!Comparable<W<X>>);

template struct W<X>;   // this instantiation should work
                        // operator== should not be instantiated
```

Here is the Godbolt example: https://godbolt.org/g/Vp8HVX

The relevant passage from N4750 is 17.8.2/10:

> An explicit instantiation that names a class template specialization is also an explicit instantiation of the
same kind (declaration or definition) of each of its members (not including members inherited from base
classes and members that are templates) that has not been previously explicitly specialized in the translation unit containing the explicit instantiation, **provided that the associated constraints, if any, of that member are satisfied by the template arguments of the explicit instantiation** (17.4.2, 17.4.1), except as described below. [ Note: In addition, it will typically be an explicit instantiation of certain implementation-dependent data about the class. —end note ]

GCC also does not implement this feature. For why I find this feature important, see this blog post: https://akrzemi1.wordpress.com/2016/09/21/concepts-lite-vs-enable_if/

**Comment by saarraz** [comment]
Hey, you're welcome, and thanks for the kind words and report.
Nice catch! It does seem like an important feature and not a hard one to implement, hopefully will have something soon.

**Comment by saarraz** [comment]
This was implemented a while back, forgot to update the issue
