### ISSUE TITLE
Not all concepts features enabled in c++2a mode, behavior different across platforms?

### ISSUE THREAD

**Issue by tzakharko** [saarraz/clang-concepts-old#70]
The clang-concepts version currently on Compiler Explorer accepts all the Concepts features when I pass in `-std=c++2a` (example: https://godbolt.org/z/DcQdFx). However, this is not the case for the clang build my local machine (macOS, clang-concepts 7dd64, llvm-project b26f96). If I try to compile this snippet, I get a bunch of errors that suggest that only basic features like concept definition and require expressions are supported. To get the full implementation, I have to pass in `-Xclang -fconcepts-ts`. Is it intended behavior or am I missing something? Also, it it intended that it behaves differently on my local toolchain vs. Compiler Explorer version?

**Comment by saarraz** [comment]
The compiler explorer version passes in - fconcepts-ts automatically.

**Comment by tzakharko** [comment]
Ah, that would explain it. Just for my curiosity, is there a reason to still hide some of the features behind the flag?

**Comment by saarraz** [comment]
Richard Smith wanted some stability before exporting this to C++2a IIRC.
I guess it'll happen once more things are merged in.

**Comment by tzakharko** [comment]
Fair enough. I am closing this then.
