### ISSUE TITLE
Assertion failure parsing lambda with initializer

### ISSUE THREAD

**Issue by davidstone** [saarraz/clang-concepts-old#71]
The following translation unit causes an assertion failure on the latest commit:

	void f() {
		[x = 0]{};
	}

With the following message:

clang-9: ../tools/clang/lib/Sema/TypeLocBuilder.cpp:160: clang::TypeLoc clang::TypeLocBuilder::pushImpl(clang::QualType, size_t, unsigned int): Assertion `Capacity - Index == TypeLoc::getFullDataSizeForType(T) && "incorrect data size provided to CreateTypeSourceInfo!"' failed.
Stack dump:
0.	Program arguments: /home/david/llvm-concepts/build/bin/clang-9 -cc1 -triple x86_64-unknown-linux-gnu -emit-obj -mrelax-all -disable-free -main-file-name main.cpp -mrelocation-model static -mthread-model posix -mdisable-fp-elim -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -fuse-init-array -target-cpu x86-64 -dwarf-column-info -debugger-tuning=gdb -coverage-notes-file /dev/null.gcno -resource-dir /home/david/llvm-concepts/build/lib/clang/9.0.0 -internal-isystem /usr/lib/gcc/x86_64-pc-linux-gnu/9.1.0/include/g++-v9 -internal-isystem /usr/lib/gcc/x86_64-pc-linux-gnu/9.1.0/include/g++-v9/x86_64-pc-linux-gnu -internal-isystem /usr/lib/gcc/x86_64-pc-linux-gnu/9.1.0/include/g++-v9/backward -internal-isystem /usr/local/include -internal-isystem /home/david/llvm-concepts/build/lib/clang/9.0.0/include -internal-externc-isystem /include -internal-externc-isystem /usr/include -std=c++2a -fdeprecated-macro -fdebug-compilation-dir /home/david/test -ferror-limit 19 -fmessage-length 0 -fno-implicit-modules -fobjc-runtime=gcc -fcxx-exceptions -fexceptions -fdiagnostics-show-option -fcolor-diagnostics -o /dev/null -x c++ source/main.cpp 
1.	source/main.cpp:2:8: current parser token ']'
2.	source/main.cpp:1:10: parsing function body 'f'
3.	source/main.cpp:1:10: in compound statement ('{}')
 #0 0x00000000017d53dd PrintStackTraceSignalHandler(void*) (.llvm.1351421673878325692) (/home/david/llvm-concepts/build/bin/clang-9+0x17d53dd)
 #1 0x00000000017d2b1e llvm::sys::RunSignalHandlers() (/home/david/llvm-concepts/build/bin/clang-9+0x17d2b1e)
 #2 0x00000000017d5888 SignalHandler(int) (/home/david/llvm-concepts/build/bin/clang-9+0x17d5888)
 #3 0x00007f680b302680 __restore_rt (/lib64/libpthread.so.0+0x14680)
 #4 0x00007f680ad14cc1 raise (/lib64/libc.so.6+0x38cc1)
 #5 0x00007f680acfe535 abort (/lib64/libc.so.6+0x22535)
 #6 0x00007f680acfe40f _nl_load_domain.cold (/lib64/libc.so.6+0x2240f)
 #7 0x00007f680ad0c712 (/lib64/libc.so.6+0x30712)
 #8 0x00000000039a6f10 clang::TypeLocBuilder::pushImpl(clang::QualType, unsigned long, unsigned int) (/home/david/llvm-concepts/build/bin/clang-9+0x39a6f10)
 #9 0x00000000036735d1 clang::Sema::buildLambdaInitCaptureInitialization(clang::SourceLocation, bool, clang::SourceLocation, llvm::Optional<unsigned int>, clang::IdentifierInfo*, bool, clang::Expr*&) (/home/david/llvm-concepts/build/bin/clang-9+0x36735d1)
#10 0x0000000003100fa8 clang::Parser::ParseLambdaIntroducer(clang::LambdaIntroducer&, clang::Parser::LambdaIntroducerTentativeParse*) (/home/david/llvm-concepts/build/bin/clang-9+0x3100fa8)
#11 0x00000000030ffe01 clang::Parser::ParseLambdaExpression() (/home/david/llvm-concepts/build/bin/clang-9+0x30ffe01)
#12 0x00000000030eea62 clang::Parser::ParseCastExpression(clang::Parser::CastParseOption, bool, bool&, clang::Parser::TypeCastState, bool) (/home/david/llvm-concepts/build/bin/clang-9+0x30eea62)
#13 0x00000000030e7c25 clang::Parser::ParseAssignmentExpression(clang::Parser::TypeCastState) (/home/david/llvm-concepts/build/bin/clang-9+0x30e7c25)
#14 0x0000000003142995 clang::Parser::ParseExprStatement(clang::Parser::ParsedStmtContext) (/home/david/llvm-concepts/build/bin/clang-9+0x3142995)
#15 0x00000000031407e9 clang::Parser::ParseStatementOrDeclarationAfterAttributes(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::ParsedStmtContext, clang::SourceLocation*, clang::Parser::ParsedAttributesWithRange&) (/home/david/llvm-concepts/build/bin/clang-9+0x31407e9)
#16 0x000000000314012b clang::Parser::ParseStatementOrDeclaration(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::ParsedStmtContext, clang::SourceLocation*) (/home/david/llvm-concepts/build/bin/clang-9+0x314012b)
#17 0x000000000314a241 clang::Parser::ParseCompoundStatementBody(bool) (/home/david/llvm-concepts/build/bin/clang-9+0x314a241)
#18 0x000000000314b1aa clang::Parser::ParseFunctionStatementBody(clang::Decl*, clang::Parser::ParseScope&) (/home/david/llvm-concepts/build/bin/clang-9+0x314b1aa)
#19 0x0000000003099a9d clang::Parser::ParseFunctionDefinition(clang::ParsingDeclarator&, clang::Parser::ParsedTemplateInfo const&, clang::Parser::LateParsedAttrList*) (/home/david/llvm-concepts/build/bin/clang-9+0x3099a9d)
#20 0x00000000030b8c76 clang::Parser::ParseDeclGroup(clang::ParsingDeclSpec&, clang::DeclaratorContext, clang::SourceLocation*, clang::Parser::ForRangeInit*) (/home/david/llvm-concepts/build/bin/clang-9+0x30b8c76)
#21 0x0000000003098504 clang::Parser::ParseDeclOrFunctionDefInternal(clang::Parser::ParsedAttributesWithRange&, clang::ParsingDeclSpec&, clang::AccessSpecifier) (/home/david/llvm-concepts/build/bin/clang-9+0x3098504)
#22 0x0000000003097ddd clang::Parser::ParseDeclarationOrFunctionDefinition(clang::Parser::ParsedAttributesWithRange&, clang::ParsingDeclSpec*, clang::AccessSpecifier) (/home/david/llvm-concepts/build/bin/clang-9+0x3097ddd)
#23 0x0000000003096cfc clang::Parser::ParseExternalDeclaration(clang::Parser::ParsedAttributesWithRange&, clang::ParsingDeclSpec*) (/home/david/llvm-concepts/build/bin/clang-9+0x3096cfc)
#24 0x000000000309477d clang::Parser::ParseTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&, bool) (/home/david/llvm-concepts/build/bin/clang-9+0x309477d)
#25 0x00000000030940f7 clang::Parser::ParseFirstTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&) (/home/david/llvm-concepts/build/bin/clang-9+0x30940f7)
#26 0x000000000308fb7d clang::ParseAST(clang::Sema&, bool, bool) (/home/david/llvm-concepts/build/bin/clang-9+0x308fb7d)
#27 0x0000000001fca5a8 clang::FrontendAction::Execute() (/home/david/llvm-concepts/build/bin/clang-9+0x1fca5a8)
#28 0x0000000001f60288 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/home/david/llvm-concepts/build/bin/clang-9+0x1f60288)
#29 0x000000000207b9d2 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/home/david/llvm-concepts/build/bin/clang-9+0x207b9d2)
#30 0x00000000007bfdf3 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/home/david/llvm-concepts/build/bin/clang-9+0x7bfdf3)
#31 0x00000000007bda6f main (/home/david/llvm-concepts/build/bin/clang-9+0x7bda6f)
#32 0x00007f680acfff1b __libc_start_main (/lib64/libc.so.6+0x23f1b)
#33 0x00000000007ba88a _start (/home/david/llvm-concepts/build/bin/clang-9+0x7ba88a)
clang-9: error: unable to execute command: Aborted (core dumped)
clang-9: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 9.0.0 (https://github.com/saarraz/clang-concepts.git 7dd64003b1659ec306875c2c78c7ce553459b1a1) (https://github.com/llvm-mirror/llvm.git d5826c99ce56037aa7a1434717cd291522ec4613)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/david/llvm-concepts/build/bin
clang-9: note: diagnostic msg: PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace, preprocessed source, and associated run script.
clang-9: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang-9: note: diagnostic msg: /tmp/main-a591c7.cpp
clang-9: note: diagnostic msg: /tmp/main-a591c7.sh
clang-9: note: diagnostic msg: 

********************

**Comment by saarraz** [comment]
Fixed in latest commit.
