### ISSUE TITLE
Assertion failure with fold expression in type-deduced member variable template of variadic class template

### ISSUE THREAD

**Issue by davidstone** [saarraz/clang-concepts-old#72]
The following translation unit causes an assertion failure on the latest commit:

	template<bool... xs>
	struct concatenate_view_iterator {
		template<typename>
		static inline auto any_is_category = (... and xs);
	
		void f() {
			any_is_category<int>;
		}
	};

With the following message:

clang-9: ../tools/clang/include/clang/AST/TemplateBase.h:360: unsigned int clang::TemplateArgument::pack_size() const: Assertion `getKind() == Pack' failed.
Stack dump:
0.	Program arguments: /home/david/llvm-concepts/build/bin/clang-9 -cc1 -triple x86_64-unknown-linux-gnu -emit-obj -mrelax-all -disable-free -main-file-name test.cpp -mrelocation-model static -mthread-model posix -mdisable-fp-elim -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -fuse-init-array -target-cpu x86-64 -dwarf-column-info -debugger-tuning=gdb -coverage-notes-file /dev/null.gcno -resource-dir /home/david/llvm-concepts/build/lib/clang/9.0.0 -I ../include -internal-isystem /home/david/llvm-concepts/build/bin/../include/c++/v1 -internal-isystem /usr/local/include -internal-isystem /home/david/llvm-concepts/build/lib/clang/9.0.0/include -internal-externc-isystem /include -internal-externc-isystem /usr/include -std=c++2a -fdeprecated-macro -fdebug-compilation-dir /home/david/tm5/bi2/build-clang-debug -ferror-limit 19 -fmessage-length 0 -fno-implicit-modules -fobjc-runtime=gcc -fcxx-exceptions -fexceptions -fdiagnostics-show-option -fcolor-diagnostics -fconcepts-ts -o /dev/null -x c++ ../source/containers/algorithms/test.cpp 
1.	../source/containers/algorithms/test.cpp:7:23: current parser token ';'
2.	../source/containers/algorithms/test.cpp:2:1: parsing struct/union/class body 's'
3.	../source/containers/algorithms/test.cpp:6:11: parsing function body 's::f'
4.	../source/containers/algorithms/test.cpp:6:11: in compound statement ('{}')
 #0 0x00000000017d53dd PrintStackTraceSignalHandler(void*) (.llvm.1351421673878325692) (/home/david/llvm-concepts/build/bin/clang-9+0x17d53dd)
 #1 0x00000000017d2b1e llvm::sys::RunSignalHandlers() (/home/david/llvm-concepts/build/bin/clang-9+0x17d2b1e)
 #2 0x00000000017d5888 SignalHandler(int) (/home/david/llvm-concepts/build/bin/clang-9+0x17d5888)
 #3 0x00007f215aac4680 __restore_rt (/lib64/libpthread.so.0+0x14680)
 #4 0x00007f215a4d6cc1 raise (/lib64/libc.so.6+0x38cc1)
 #5 0x00007f215a4c0535 abort (/lib64/libc.so.6+0x22535)
 #6 0x00007f215a4c040f _nl_load_domain.cold (/lib64/libc.so.6+0x2240f)
 #7 0x00007f215a4ce712 (/lib64/libc.so.6+0x30712)
 #8 0x00000000039598c0 clang::Sema::CheckParameterPacksForExpansion(clang::SourceLocation, clang::SourceRange, llvm::ArrayRef<std::pair<llvm::PointerUnion<clang::TemplateTypeParmType const*, clang::NamedDecl*>, clang::SourceLocation> >, clang::MultiLevelTemplateArgumentList const&, bool&, bool&, llvm::Optional<unsigned int>&) (/home/david/llvm-concepts/build/bin/clang-9+0x39598c0)
 #9 0x000000000390c81f clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformCXXFoldExpr(clang::CXXFoldExpr*) (/home/david/llvm-concepts/build/bin/clang-9+0x390c81f)
#10 0x0000000003953240 clang::Sema::InstantiateVariableInitializer(clang::VarDecl*, clang::VarDecl*, clang::MultiLevelTemplateArgumentList const&) (/home/david/llvm-concepts/build/bin/clang-9+0x3953240)
#11 0x000000000393d9ec clang::Sema::BuildVariableInstantiation(clang::VarDecl*, clang::VarDecl*, clang::MultiLevelTemplateArgumentList const&, llvm::SmallVector<clang::Sema::LateInstantiatedAttribute, 16u>*, clang::DeclContext*, clang::LocalInstantiationScope*, bool, clang::VarTemplateSpecializationDecl*) (/home/david/llvm-concepts/build/bin/clang-9+0x393d9ec)
#12 0x000000000394ecbc clang::TemplateDeclInstantiator::VisitVarTemplateSpecializationDecl(clang::VarTemplateDecl*, clang::VarDecl*, void*, clang::TemplateArgumentListInfo const&, llvm::ArrayRef<clang::TemplateArgument>, clang::VarTemplateSpecializationDecl*) (/home/david/llvm-concepts/build/bin/clang-9+0x394ecbc)
#13 0x0000000003952e05 clang::Sema::BuildVarTemplateInstantiation(clang::VarTemplateDecl*, clang::VarDecl*, clang::TemplateArgumentList const&, clang::TemplateArgumentListInfo const&, llvm::SmallVectorImpl<clang::TemplateArgument>&, clang::SourceLocation, void*, llvm::SmallVector<clang::Sema::LateInstantiatedAttribute, 16u>*, clang::LocalInstantiationScope*) (/home/david/llvm-concepts/build/bin/clang-9+0x3952e05)
#14 0x000000000380e628 clang::Sema::CheckVarTemplateId(clang::VarTemplateDecl*, clang::SourceLocation, clang::SourceLocation, clang::TemplateArgumentListInfo const&) (/home/david/llvm-concepts/build/bin/clang-9+0x380e628)
#15 0x000000000380f4a9 clang::Sema::CheckVarTemplateId(clang::CXXScopeSpec const&, clang::DeclarationNameInfo const&, clang::VarTemplateDecl*, clang::SourceLocation, clang::TemplateArgumentListInfo const*) (/home/david/llvm-concepts/build/bin/clang-9+0x380f4a9)
#16 0x0000000003611e84 clang::Sema::BuildPossibleImplicitMemberExpr(clang::CXXScopeSpec const&, clang::SourceLocation, clang::LookupResult&, clang::TemplateArgumentListInfo const*, clang::Scope const*) (/home/david/llvm-concepts/build/bin/clang-9+0x3611e84)
#17 0x00000000034f2ecd clang::Sema::ActOnIdExpression(clang::Scope*, clang::CXXScopeSpec&, clang::SourceLocation, clang::UnqualifiedId&, bool, bool, clang::CorrectionCandidateCallback*, bool, clang::Token*) (/home/david/llvm-concepts/build/bin/clang-9+0x34f2ecd)
#18 0x00000000030fe74b clang::Parser::tryParseCXXIdExpression(clang::CXXScopeSpec&, bool, clang::Token&) (/home/david/llvm-concepts/build/bin/clang-9+0x30fe74b)
#19 0x00000000030ffd4e clang::Parser::ParseCXXIdExpression(bool) (/home/david/llvm-concepts/build/bin/clang-9+0x30ffd4e)
#20 0x00000000030eccdd clang::Parser::ParseCastExpression(clang::Parser::CastParseOption, bool, bool&, clang::Parser::TypeCastState, bool) (/home/david/llvm-concepts/build/bin/clang-9+0x30eccdd)
#21 0x00000000030e7c25 clang::Parser::ParseAssignmentExpression(clang::Parser::TypeCastState) (/home/david/llvm-concepts/build/bin/clang-9+0x30e7c25)
#22 0x0000000003142995 clang::Parser::ParseExprStatement(clang::Parser::ParsedStmtContext) (/home/david/llvm-concepts/build/bin/clang-9+0x3142995)
#23 0x00000000031407e9 clang::Parser::ParseStatementOrDeclarationAfterAttributes(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::ParsedStmtContext, clang::SourceLocation*, clang::Parser::ParsedAttributesWithRange&) (/home/david/llvm-concepts/build/bin/clang-9+0x31407e9)
#24 0x000000000314012b clang::Parser::ParseStatementOrDeclaration(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::ParsedStmtContext, clang::SourceLocation*) (/home/david/llvm-concepts/build/bin/clang-9+0x314012b)
#25 0x000000000314a241 clang::Parser::ParseCompoundStatementBody(bool) (/home/david/llvm-concepts/build/bin/clang-9+0x314a241)
#26 0x000000000314b1aa clang::Parser::ParseFunctionStatementBody(clang::Decl*, clang::Parser::ParseScope&) (/home/david/llvm-concepts/build/bin/clang-9+0x314b1aa)
#27 0x00000000030a4953 clang::Parser::ParseLexedMethodDef(clang::Parser::LexedMethod&) (/home/david/llvm-concepts/build/bin/clang-9+0x30a4953)
#28 0x00000000030a33b5 clang::Parser::ParseLexedMethodDefs(clang::Parser::ParsingClass&) (/home/david/llvm-concepts/build/bin/clang-9+0x30a33b5)
#29 0x00000000030da17d clang::Parser::ParseCXXMemberSpecification(clang::SourceLocation, clang::SourceLocation, clang::Parser::ParsedAttributesWithRange&, unsigned int, clang::Decl*) (/home/david/llvm-concepts/build/bin/clang-9+0x30da17d)
#30 0x00000000030d704a clang::Parser::ParseClassSpecifier(clang::tok::TokenKind, clang::SourceLocation, clang::DeclSpec&, clang::Parser::ParsedTemplateInfo const&, clang::AccessSpecifier, bool, clang::Parser::DeclSpecContext, clang::Parser::ParsedAttributesWithRange&) (/home/david/llvm-concepts/build/bin/clang-9+0x30d704a)
#31 0x00000000030b2989 clang::Parser::ParseDeclarationSpecifiers(clang::DeclSpec&, clang::Parser::ParsedTemplateInfo const&, clang::AccessSpecifier, clang::Parser::DeclSpecContext, clang::Parser::LateParsedAttrList*) (/home/david/llvm-concepts/build/bin/clang-9+0x30b2989)
#32 0x0000000003153064 clang::Parser::ParseSingleDeclarationAfterTemplate(clang::DeclaratorContext, clang::Parser::ParsedTemplateInfo const&, clang::ParsingDeclRAIIObject&, clang::SourceLocation&, clang::ParsedAttributes&, clang::AccessSpecifier) (/home/david/llvm-concepts/build/bin/clang-9+0x3153064)
#33 0x00000000031521d4 clang::Parser::ParseTemplateDeclarationOrSpecialization(clang::DeclaratorContext, clang::SourceLocation&, clang::ParsedAttributes&, clang::AccessSpecifier) (/home/david/llvm-concepts/build/bin/clang-9+0x31521d4)
#34 0x0000000003151a2f clang::Parser::ParseDeclarationStartingWithTemplate(clang::DeclaratorContext, clang::SourceLocation&, clang::ParsedAttributes&, clang::AccessSpecifier) (/home/david/llvm-concepts/build/bin/clang-9+0x3151a2f)
#35 0x00000000030b1bf0 clang::Parser::ParseDeclaration(clang::DeclaratorContext, clang::SourceLocation&, clang::Parser::ParsedAttributesWithRange&) (/home/david/llvm-concepts/build/bin/clang-9+0x30b1bf0)
#36 0x00000000030960d4 clang::Parser::ParseExternalDeclaration(clang::Parser::ParsedAttributesWithRange&, clang::ParsingDeclSpec*) (/home/david/llvm-concepts/build/bin/clang-9+0x30960d4)
#37 0x000000000309477d clang::Parser::ParseTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&, bool) (/home/david/llvm-concepts/build/bin/clang-9+0x309477d)
#38 0x00000000030940f7 clang::Parser::ParseFirstTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&) (/home/david/llvm-concepts/build/bin/clang-9+0x30940f7)
#39 0x000000000308fb7d clang::ParseAST(clang::Sema&, bool, bool) (/home/david/llvm-concepts/build/bin/clang-9+0x308fb7d)
#40 0x0000000001fca5a8 clang::FrontendAction::Execute() (/home/david/llvm-concepts/build/bin/clang-9+0x1fca5a8)
#41 0x0000000001f60288 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/home/david/llvm-concepts/build/bin/clang-9+0x1f60288)
#42 0x000000000207b9d2 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/home/david/llvm-concepts/build/bin/clang-9+0x207b9d2)
#43 0x00000000007bfdf3 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/home/david/llvm-concepts/build/bin/clang-9+0x7bfdf3)
#44 0x00000000007bda6f main (/home/david/llvm-concepts/build/bin/clang-9+0x7bda6f)
#45 0x00007f215a4c1f1b __libc_start_main (/lib64/libc.so.6+0x23f1b)
#46 0x00000000007ba88a _start (/home/david/llvm-concepts/build/bin/clang-9+0x7ba88a)
clang-9: error: unable to execute command: Aborted (core dumped)
clang-9: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 9.0.0 (https://github.com/saarraz/clang-concepts.git 7dd64003b1659ec306875c2c78c7ce553459b1a1) (https://github.com/llvm-mirror/llvm.git d5826c99ce56037aa7a1434717cd291522ec4613)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/david/llvm-concepts/build/bin
clang-9: note: diagnostic msg: PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace, preprocessed source, and associated run script.
clang-9: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang-9: note: diagnostic msg: /tmp/test-3b47ca.cpp
clang-9: note: diagnostic msg: /tmp/test-3b47ca.sh
clang-9: note: diagnostic msg: 

********************

Since I do not have easy access to a build of clang master with assertions enabled, it's possible that this has nothing to do with your code.

**Comment by saarraz** [comment]
I think this is indeed not a problem with my code, It'd be great if you can see if this indeed happens in a trunk build.

**Comment by davidstone** [comment]
Bug in clang master: https://bugs.llvm.org/show_bug.cgi?id=42758
