### ISSUE TITLE
Normal form of `C<T> && C<T>` should be `C<T>`, as far as I know

### ISSUE THREAD

**Issue by Quuxplusone** [saarraz/clang-concepts-old#74]
https://concepts.godbolt.org/z/i1FsqB

Clang is happy with this redeclaration of a template:
```
template<C T> requires C<T>
struct foo;

template<class T> requires C<T> && C<T>
struct foo;
``` 
But Clang complains about this redeclaration:
```
template<C T> requires C<T>
struct foo;

template<class T> requires C<T>
struct foo;
```
```
<source>:11:8: error: redeclaration 'template<class T>  requires  C<T> and C<T> struct foo' with different constraints
   11 | struct foo;
      |        ^~~
<source>:8:8: note: original declaration appeared here
    8 | struct foo;
      |        ^~~
<source>:11:8: error: 'foo<T>' does not match any declaration
   11 | struct foo;
      |        ^~~
```

My understanding is that `C<T>` and `C<T> && C<T>` should have exactly the same normal form, and Clang shouldn't be complaining about the latter.

Incidentally, it also seems like the error message is printing out extra whitespace around the `requires` keyword — "`'template<class T>  requires  C<T> and C<T> struct foo'`" — but maybe there's a reason for that.

**Comment by saarraz** [comment]
I think the requirement is that the template-heads be equivalent, not that they have the same normalized constraints: http://eel.is/c++draft/temp.decls#temp.class-3

**Comment by Quuxplusone** [comment]
If that's the case, then it sounds like the program involving
```
template<C T> requires C<T>
struct foo;

template<class T> requires C<T> && C<T>
struct foo;
```
would be ill-formed. Is your contention that that program is IFNDR and that it would be prohibitively expensive for Clang to issue a diagnostic?

**Comment by saarraz** [comment]
What makes you say that this is IFNDR?

**Comment by saarraz** [comment]
I am issuing a diagnostic for this https://concepts.godbolt.org/z/JfGxpu

**Comment by Quuxplusone** [comment]
Oops, I have already confused myself, but I think what happened is that I was looking at **GCC's** output. **GCC** doesn't diagnose
```
template<C T> requires C<T>
struct foo;

template<class T> requires C<T> && C<T>
struct foo;
```
but you're right, your Clang branch does diagnose it. Okay, so as long as the requirement is that the template-heads be identical, and as long as I stop accidentally looking at GCC's output, I think we're done here. Sorry for the noise. :)
