### ISSUE TITLE
cmcstl2 ICE 2

### ISSUE THREAD

**Issue by cjdb** [saarraz/clang-concepts-old#8]
Thanks for addressing the last ICE that I had so quickly! I've gotten another ICE while trying to build cmcstl2/clang-concepts, results below.

[meta-5542c8.cpp.txt](https://github.com/saarraz/clang-concepts/files/2278861/meta-5542c8.cpp.txt)
[meta-5542c8.sh.txt](https://github.com/saarraz/clang-concepts/files/2278862/meta-5542c8.sh.txt)

**Comment by cjdb** [comment]
I wasn't aware that #2 wasn't closed. Would you prefer I close this and move back there?

**Comment by saarraz** [comment]
Hey, again, it'd be great if you could narrow this down. (is #2 a different ICE?)

**Comment by cjdb** [comment]
This ICE still happens, I'll get you something closer to a minimal build ASAP.

**Comment by cjdb** [comment]
> error: template template argument 'compose' must not be more constrained than template template parameter 'C'

This is beautiful.

**Comment by saarraz** [comment]
Hey, finally got back to this. Can you narrow this down?

**Comment by marehr** [comment]
I think this can be closed; I tried to build his branch and got no ICE for the tests.

**Comment by saarraz** [comment]
Also tried to compile the attached examples and no ICE. Closing
