### ISSUE TITLE
'associated constraints differ in template redeclaration' diagnostic applied to unrelated types

### ISSUE THREAD

**Issue by cjdb** [saarraz/clang-concepts-old#9]
Here's a snippet of diagnostics that I get when trying to build cmcstl2:

```cpp
/c/Users/ChristopherDiBella/projects/cmcstl2/cmcstl2/include/stl2/meta/meta.hpp:136:19: error: associated constraints differ in template redeclaration
        template <Trait T>
                  ^
/c/Users/ChristopherDiBella/projects/cmcstl2/cmcstl2/include/stl2/meta/meta_fwd.hpp:66:29: note: previous template declaration is here
        template <template <typename...> class C, typename... Ts>
                            ^
```

The problem is that these two types are completely unrelated.

```cpp
// from meta.hpp:136
template <Trait T>
using _t = typename T::type;

// from meta_fwd.hpp:66
template <template <typename...> class C, typename... Ts>
struct defer;
```

**Comment by saarraz** [comment]
It would greatly shorten the time it takes to debug this if yiu

**Comment by saarraz** [comment]
It would greatly shorten the time it takes to solve this if you can narrow it down to a standalone snippet that triggers the bug

**Comment by cjdb** [comment]
Hopefully minimal enough! https://godbolt.org/g/cV3xrH

**Comment by cjdb** [comment]
Slightly smaller: https://godbolt.org/g/S5Do8R (also note that I changed the second `using _t` to `using _t2`).

**Comment by CaseyCarter** [comment]
It's smaller without the headers or the namespaces: https://godbolt.org/g/Epi2my
(Compiler guys always want library-free repros.)

**Comment by saarraz** [comment]
This is the smallest I've got this https://godbolt.org/g/ey323r
It seems its complaint is that you're trying to pass a template with constraints to a template-template parameter without constraints. I believe this is indeed a mistake to complain about this standard-wise, but I'll verify this and get back to you

**Comment by saarraz** [comment]
And in any case the error message should indeed be more indicative 😅

**Comment by saarraz** [comment]
OK this is indeed a bug - http://eel.is/c++draft/temp.arg.template#3 (see last example here). I'll fix this in the coming days probably.

**Comment by saarraz** [comment]
OK it should be fixed now (might take a while to show up on compiler explorer). Let me know if it's working for you now (and what you think of the error messages)

**Comment by cjdb** [comment]
Thanks! I can now start working on eliminating introducer syntax 😢

**Comment by cjdb** [comment]
> error: template template argument 'compose' must not be more constrained than template template parameter 'C'

This is beautiful.

**Comment by saarraz** [comment]
Glad you liked it 😀 I rephrased that message like 5 times
